# Generated by Django 4.2.5 on 2023-10-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateOfBirth',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='pass123', max_length=40),
            preserve_default=False,
        ),
    ]
